#!/usr/bin/env python3
from __future__ import annotations
import argparse, json
from datetime import datetime, timezone
from pathlib import Path

POLICY = "Reference policy: extract reusable principles only; do not copy logos, trademarks, proprietary illustrations, or exact layouts."

def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")

def scaffold(root: Path, project_name: str) -> None:
    now = datetime.now(timezone.utc).isoformat()
    brief = {
        "artic_version": "0.1.0",
        "project": {
            "name": project_name,
            "type": "homepage",
            "description": "Smoke-test project generated by Artic.",
            "target_users": ["early adopters", "buyers"],
            "primary_goal": "waitlist signup",
        },
        "style": {
            "desired_impression": ["trustworthy", "modern", "clear"],
            "selected_preset": "clean-saas",
            "likes": ["clear hierarchy", "premium whitespace"],
            "dislikes": ["generic gradients", "clutter"],
            "fixed_assets": {"colors": [], "fonts": [], "logo": None},
            "search_facets": ["homepage", "clean-saas", "trust", "mobile-first", "wcag"],
        },
        "references": [],
        "implementation": {"stack": "unspecified", "mobile_first": True, "accessibility": "WCAG AA"},
        "copy_policy": "extract reusable principles only; do not copy logos, trademarks, proprietary illustrations, or exact layouts",
    }
    references = {
        "selected_sources": [
            {"id": "google-design-md", "reason": "output contract and validation"},
            {"id": "voltagent-awesome-design-md", "reason": "homepage and SaaS style candidates"},
            {"id": "material-design", "reason": "token and accessibility discipline"},
        ],
        "synthesis": "Clean SaaS hierarchy with token discipline and mobile-first accessibility.",
    }
    state = {"artic_version": "0.1.0", "last_generated_at": now, "status": "scaffolded"}
    write(root / ".artic" / "brief.json", json.dumps(brief, indent=2, ensure_ascii=False) + "\n")
    write(root / ".artic" / "references.json", json.dumps(references, indent=2, ensure_ascii=False) + "\n")
    write(root / ".artic" / "state.json", json.dumps(state, indent=2, ensure_ascii=False) + "\n")
    write(root / "docs" / "artic-brief.md", f"# Artic Brief\n\nProject: {project_name}\n\n{POLICY}\n")
    design = f'''---
version: alpha
name: "{project_name}"
description: "Clean SaaS homepage design system generated by Artic."
colors:
  primary: "#1F4FD8"
  secondary: "#465064"
  accent: "#7C3AED"
  surface: "#FFFFFF"
  neutral: "#F6F8FB"
  text: "#111827"
  muted: "#6B7280"
  border: "#DDE3EA"
typography:
  h1:
    fontFamily: Inter
    fontSize: 4rem
    fontWeight: 760
    lineHeight: 1.05
    letterSpacing: "-0.04em"
  body-md:
    fontFamily: Inter
    fontSize: 1rem
    fontWeight: 400
    lineHeight: 1.65
rounded:
  sm: 6px
  md: 12px
  lg: 20px
spacing:
  sm: 8px
  md: 16px
  lg: 24px
components:
  button-primary:
    backgroundColor: "{{colors.primary}}"
    textColor: "#FFFFFF"
    rounded: "{{rounded.md}}"
    padding: 12px
  button-secondary:
    backgroundColor: "{{colors.secondary}}"
    textColor: "#FFFFFF"
    rounded: "{{rounded.md}}"
    padding: 12px
  accent-badge:
    backgroundColor: "{{colors.accent}}"
    textColor: "#FFFFFF"
    rounded: "{{rounded.sm}}"
    padding: "{{spacing.sm}}"
  card:
    backgroundColor: "{{colors.surface}}"
    textColor: "{{colors.text}}"
    rounded: "{{rounded.lg}}"
    padding: "{{spacing.lg}}"
  divider:
    backgroundColor: "{{colors.border}}"
    height: 1px
    width: 100%
  muted-panel:
    backgroundColor: "{{colors.neutral}}"
    textColor: "{{colors.muted}}"
    rounded: "{{rounded.md}}"
    padding: "{{spacing.md}}"
---

## Overview

Clean, trustworthy, mobile-first SaaS homepage direction. {POLICY}

## Colors

Use role-based colors and preserve contrast.

## Typography

Use clear hierarchy and readable body text.

## Layout

Use mobile-first sections and consistent spacing.

## Elevation & Depth

Use subtle surfaces and restrained shadows.

## Shapes

Use the documented radius scale.

## Components

Buttons, cards, and forms must use documented tokens.

## Do's and Don'ts

Do follow tokens and synthesis. Don't clone references.
'''
    write(root / "DESIGN.md", design)
    write(root / "docs" / "design-rules.md", f"# Design Rules\n\n{POLICY}\n\n## Selected Reference Synthesis\n\nClean SaaS + Material token discipline.\n")
    write(root / "docs" / "design-qa-checklist.md", f"# Artic Design QA Checklist\n\n{POLICY}\n\n- [ ] Tokens are used consistently.\n- [ ] CTA hierarchy is clear.\n- [ ] Mobile layout works.\n")
    write(root / "docs" / "homepage-design-prompt.md", f"# Homepage Implementation Prompt\n\nUse DESIGN.md and docs/design-rules.md.\n\n{POLICY}\n")

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True)
    parser.add_argument("--project-name", default="Artic Smoke Project")
    args = parser.parse_args()
    scaffold(Path(args.root), args.project_name)
    print(f"Scaffolded Artic files at {Path(args.root).resolve()}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
